### PR TITLE
Add BSL Tools and Questionnaire

### PR DESCRIPTION
**Pull request by fkellner**
Stepper, (interactive) ASTs and Example Quizzes in HTML, Quizzes also in PDF in a separate Chapter at the end. For more information on use see the respective projects:
https://github.com/se-tuebingen/bsl-tools
https://github.com/se-tuebingen/questionnaire (Questionnaire)

### CODE REVIEW

**Review by linususer — APPROVED** [review]
LGTM!

**Comment by Ludwig-Work** [comment]
LGTM too.

The only drawback I found is that the quiz with the `cond` expression expands so wide that it doesn't fit on the page and you need to scroll sideways.
grafik

Increasing the `max-width` of the `maincolumn` div to e.g. `1000px` instead of `700px` improves this, but still doesn't fix it completely: The entire tree expansion together with the side notes would be wider than my laptop screen.
grafik
Not sure if that would be desired though.
Also, I couldn't find where the HTML/CSS settings are actually done in the source. 👀 

Either ignore this and accept that you have to scroll sideways in the tree, or perhaps change the example to one where the tree is not as wide but rather deep?

Everything else looks great to me, good quizzes, examples with the stepper, and trees.

**Comment by fkellner** [comment]
Ultimately, the tree is so wide because it should look like a tree one would draw on a blackboard and be recognizable as such - and we did not find any libraries that solved this problem well, and developing our own tree layout algorithm would have been out of scope. So when developing, we accepted that sidescrolling would become necessary. 

If you are looking for HTML/CSS settings in the source (we tried to do as little as possible and leave as much as possible to the surrounding HTML/Scribble document): 
- CSS: https://github.com/se-tuebingen/bsl-tools/blob/main/src/ressources/tree.css
- HTML is generated via Template Strings in the https://github.com/se-tuebingen/bsl-tools/blob/main/src/Production_Tree.ts module.
- If the problem is Scribble-Generated HTML: Here is an overview over the scribble elements: https://docs.racket-lang.org/scribble/core.html

**Comment by fkellner** [comment]
So yeah basically if you want to change the main column width, that is part of the HTML/CSS generated by Scribble. One could probably circumvent this just for the quiz by negative margins/absolute positioning if one really wanted, but that would probably not work consistently across all form factors.

**Comment by Ludwig-Work** [comment]
Thanks for the suggestions and explanations!

Since the example in question is based on the coding with `asBool` for `and`, which has been changed in the script as of 6d7f011, I assume that the example is no longer relevant anyway. Therefore, the best solution IMO would be to just go with a different example that doesn't have a too wide tree?

**Pull request merged**
